version: 0.2
phases:
  pre_build:
    commands:
      - echo "Comenzando el pipeline en AWS"
  build:
    commands:
      - echo "Construyendo JAR"
      - mvn clean install
  post_build:
    commands:
      - echo "Inicializando la aplicación"
      - mv target/devops-api-test-0.0.1-SNAPSHOT.jar ./
artifacts:
  files:
    - devops-api-test-0.0.1-SNAPSHOT.jar