version: 0.2
phases:
  pre_build:
    commands:
      - echo "Comenzando el pipeline en AWS"
  build:
    commands:
      - echo "Construyendo JAR"
      - mvn clean install
  install:
    runtime-versions:
      java: corretto11
  post_build:
    commands:
      - echo "Inicializando la aplicación"
      - mvn package
      - mvn sring-boot:run
artifacts:
  files:
    - devops-api-test-0.0.1-SNAPSHOT.jar
    - .ebextensions/**/*
    - deploy/**/*